services:
  - type: web
    name: student-management-backend
    env: java
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk-amd64
      - key: MAVEN_OPTS
        value: -Xmx512m